server:
  port: ${WEB_PORT:3000}

spring:
  application:
    name: mineportal-server
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mineportal}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:mineportal}
    password: ${DB_PASSWORD:mineportal}
